# Stage 1: deps — install production dependencies only
FROM node:24-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
# --ignore-scripts skips postinstall (prepare-alvamind.mjs) — we run it in builder
RUN npm ci --only=production --ignore-scripts

# Stage 2: builder — full install + build
FROM node:24-alpine AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY package.json package-lock.json ./
# Full install including devDependencies, then run postinstall for bazi-calculator
RUN npm ci --ignore-scripts
COPY . .
# Run postinstall manually after copying scripts/ so prepare-alvamind.mjs has the source
RUN npm run postinstall
RUN npm run build

# Stage 3: runner — minimal production image
FROM node:24-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV APP_DATA_DIR=/app/data

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs \
  && mkdir -p /app/data \
  && chown -R nextjs:nodejs /app/data

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
# Copy prepared bazi-calculator runtime (generated by postinstall)
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/bazi-calculator-by-alvamind/dist ./node_modules/bazi-calculator-by-alvamind/dist

USER nextjs
EXPOSE 3000

CMD ["node", "server.js"]
